trigger:
  - Desenv
  - Prod

name: $(Build.BuildId)

pr:
  - Desenv
  - Prod

variables:
  - group: thinkbitcoin-secrets

jobs:
- job: DeployVercel
  displayName: 'Deploy to Vercel'
  pool:
    name: 'ThinkBitcoinPool'
  
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: npm install
    workingDirectory: 'src'
    displayName: 'Install Dependencies'

  - task: PowerShell@2
    displayName: 'Vercel Deploy'
    inputs:
      targetType: 'inline'
      script: |
        npm install -g vercel
        cd src
        if ("$(Build.SourceBranch)" -eq "refs/heads/Prod") {
            Write-Host "Deploying to Production..."
            vercel --token $(VERCEL_TOKEN) --prod --yes
        }
        else {
            Write-Host "Deploying Preview..."
            vercel --token $(VERCEL_TOKEN) --yes
        }
    env:
      VERCEL_ORG_ID: $(VERCEL_ORG_ID)
      VERCEL_PROJECT_ID: $(VERCEL_PROJECT_ID)

  - task: PowerShell@2
    displayName: 'Sync No-IP DUC (Minikube)'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Syncing No-IP Credentials..."
        kubectl create secret opaque noip-credentials --from-literal=username=$(NOIP_EMAIL) --from-literal=password=$(NOIP_PASSWORD) -n thinkbitcoin --dry-run=client -o yaml | kubectl apply -f -
        
        Write-Host "Applying No-IP DUC Deployment..."
        kubectl apply -f devops/deploy/noip-duc.yaml
