name: thinkbitcoin-front

services:
  thinkbitcoin-front:
    build:
      context: ../../src
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:13501}
    image: thinkbitcoin-front:local
    container_name: thinkbitcoin-front
    ports:
      - "8080:80"
    restart: unless-stopped
